[project]
name = "led-matrix-zmq-hass"
version = "0.0.0"
readme = "README.md"
requires-python = ">=3.13.2"
dependencies = [
    "homeassistant>=2025.7.0",
]

[dependency-groups]
dev = [
    "mypy>=1.13.0",
    "ruff>=0.8.0",
]
