name: Check

on:
  push:

jobs:
  check-python:
    name: Check Python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          version: latest
      - name: Install dependencies
        run: uv sync
      - name: Run checks
        run: uv run ./bin/check

  check-hass-hacs:
    name: Check HASS/HACS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check HASS
        uses: home-assistant/actions/hassfest@master
      - name: Check HACS
        uses: hacs/action@main
        with:
          category: integration
